# Generated by Django 3.1.7 on 2022-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmod',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
